### ISSUE TITLE
better repo name?

### ISSUE THREAD

**Issue by YesThatAllen** [dependencies-io/ruby#2]
I don't know all the conventions in this world, but I just forked & downloaded this repo, and there's no  indication of who's product this is, or what the repo is all about.

Perhaps updating the repo name to something like `ruby-dependencies` would work? at the very least,  it wouldn't conflict with `git clone git@github.com:ruby/ruby.git`

**Comment by davegaeddert** [comment]
Appreciate the feedback. This is the naming scheme we've gone with in our [dependencies-io org namespace](https://github.com/dependencies-io) so I don't think we're going to change it right now, but will keep it in mind (it also maps to the `type: ruby` field in dependencies.yml). For now I'd just recommend `git clone git@github.com:dependencies-io/ruby.git ruby-dependencies` or something if the directory name throws you off on your machine. Hopefully it will be less of a problem when I get the README added too ;)

I'll close this for now but keep it in mind as a broader potential change. Thanks!
